package vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**

 * @author Alvaro
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    
    public VentanaPrincipal() {
        initComponents();
        ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/iconoUS.png"));
        Icon fondo = new ImageIcon(icono.getImage().getScaledInstance(IconoUS.getWidth(), IconoUS.getHeight(), Image.SCALE_DEFAULT));
        IconoUS.setIcon(fondo);
        this.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IconoUS = new javax.swing.JLabel();
        gestCuenta = new javax.swing.JButton();
        gestOperacion = new javax.swing.JButton();
        gestUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 5, 79));
        setMinimumSize(new java.awt.Dimension(530, 370));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(IconoUS);
        IconoUS.setBounds(200, 20, 104, 73);

        gestCuenta.setText("Gestionar Cuentas");
        gestCuenta.setActionCommand("Usuario");
        getContentPane().add(gestCuenta);
        gestCuenta.setBounds(320, 141, 137, 38);
        gestCuenta.getAccessibleContext().setAccessibleName("Usuario");

        gestOperacion.setText("Realizar Operación");
        gestOperacion.setToolTipText("");
        gestOperacion.setActionCommand("Usuario");
        getContentPane().add(gestOperacion);
        gestOperacion.setBounds(176, 233, 137, 38);

        gestUsuario.setText("Gestionar Usuarios");
        gestUsuario.setActionCommand("Usuario");
        getContentPane().add(gestUsuario);
        gestUsuario.setBounds(50, 140, 137, 38);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 530, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconoUS;
    public javax.swing.JButton gestCuenta;
    public javax.swing.JButton gestOperacion;
    public javax.swing.JButton gestUsuario;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
